### ISSUE TITLE
[feature] - add Quarkus open-api / swagger-ui to app backend

### ISSUE THREAD

**Issue by eformat** [redhat-scholars/backstage-workshop#10]
Might be nice from a devex point of view - to just deploy the openapi/swagger ui rather than terminal+curl from app pods.

Then add the link + openapi docs into Backstage ?

```
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-openapi</artifactId>
        </dependency>
```

**Comment by ryanj** [comment]
Backstage also includes support for an "API" resource type that might be helpful to include along with our Backend Component.  

This upstream commit is a decent example: https://github.com/Summit23DevRHEL/software-templates/commit/1b69261059d5e502351734140deba0c94fbb04cf

More API resource examples here: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/apis/petstore-api.yaml

**Comment by hpgrahsl** [comment]
work is underway to have this supported for the workshop

**Comment by hpgrahsl** [comment]
initially addressed with this already merged PR https://github.com/hpgrahsl/rhsummit23-backstage-gpts/pull/25
we might do more API resource related improvements in backstage i.e. also include similar stuff for the gateway component
