### ISSUE TITLE
[feature] - Switch to a light theme for all screenshots

### ISSUE THREAD

**Issue by alexgroom** [redhat-scholars/backstage-workshop#12]
The guide screen shots are often in dark/inverted mode for OpenShift console. Will this be the default mode for all users in the workshop? If not a lot of the screen shots will confuse since they will not match the behaviour people first see (to try and reduce the cognitive load). We shouldn't assume everyone is familiar with the UI modes.

I personally also think that the black sucks the life out the guide, but that is a much more stylistic observation ;-)

**Comment by ryanj** [comment]
Thanks for the feedback!  

My OS defaults were picked up in the shots.  I'll try switching to a light theme before we do our final pass of screenshots leading up to summit.
