### ISSUE TITLE
Typo in Welcome page of Vs Code

### ISSUE THREAD

**Issue by mcombi** [redhat-scholars/backstage-workshop#17]
Very minor issue, but in the welcome page of Vs Code, the tool is called Visual Studio Cod, without the last _e_

In my case, launched with: https://devspaces.apps.summit23-dr.w6gk.p1.openshiftapps.com/#https://github.com/Summit23DevRHEL/mcombi-backend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml

![image](https://user-images.githubusercontent.com/100132715/235083699-20938726-f480-414c-bcc8-58a2e76d6173.png)

**Comment by joshix** [comment]
![Image 4-28-23 at 02 43](https://user-images.githubusercontent.com/72905/235086371-f932d0d2-a649-4860-8478-9fd52492920e.jpg)

I think that's just a browser viewport happenstance and not a typo or bug.

**Comment by joshix** [comment]
@mcombi unless you disagree, I intend to close this issue.

**Comment by mcombi** [comment]
Ok for me
