### ISSUE TITLE
Accessing Openshift, should we highlight the fact that project was auto-created?

### ISSUE THREAD

**Issue by kdubois** [redhat-scholars/backstage-workshop#18]
I'm just wondering if we should highlight the fact that when one access the Openshift cluster with their github account, it automatically creates a project for them.    Other than it being a cool feature, it might also alleviate confusion as to why there is a project with their username already there.

**Comment by ryanj** [comment]
updated the content to mention that this resource is auto-created in the background

**Comment by joshix** [comment]
fixed by added `TIP` in 18735a2
