### ISSUE TITLE
The gitHub org name is inconsistent between guide and lab

### ISSUE THREAD

**Issue by alexgroom** [redhat-scholars/backstage-workshop#20]
Lab guide screenshots show: Summit23DevLAB
Reality when trying this lab is: Summit23DevRHEL

I appreciate this maybe a trial thing at this time, but unexpected for now.

**Comment by hpgrahsl** [comment]
THX for reporting this. The reason for this is that we have 2 test clusters to try out the workshop activities and each of the clusters indeed uses a different github org behind the scenes. And the screenshots in this case have been captured on the other instance I assume. We will fix all these issues with a final pass of screenshots before the summit lab takes places.
