### ISSUE TITLE
suggestion in template lab 2 for NAMESPACE to repeat Project note

### ISSUE THREAD

**Issue by alexgroom** [redhat-scholars/backstage-workshop#21]
At this point "Keep all the default values, while inserting your NAMESPACE value into the form inputs in place of the <NAMESPACE> string." it would be worth reminding people of the note about project = namespace you made in the previous chapter since this is the point of first use.

In the previous chapter you say "IMPORTANT Remember your Project name. You’ll specify it in Template forms as your "Namespace" value as you deploy components." and maybe this would be a good place to repeat something similar references the project either seen or created in the last chapter.

**Comment by hpgrahsl** [comment]
THX. I agree that it makes sense to repeat the important infos wherever necessary to make sure attendees will get it right.
