### ISSUE TITLE
Why does the Janus frontend template need NAMESPACE value 4 times?

### ISSUE THREAD

**Issue by alexgroom** [redhat-scholars/backstage-workshop#22]
This really about the template UX choices in the lab, because I don't understand when I'm dealing with a computer why it can't fill in NAMESPACE 4 times rather than the human. This is supposed to be a golden-path, it doesn't feel as easy as it should and makes Janus look clunky. Given everything is driven off my github id and I have logged into Janus, surely something can default all of these values?

**Comment by hpgrahsl** [comment]
I agree that it's not ideal in the way it's handled right now and so, I will look into getting to a better UX in that regard. Just to give you some context: this isn't a Janus thing at all but more of an upstream backstage aspect. AFAIK there is still no simple (out-of-the-box) way to reuse form fields from previous form sections in the current dialog/wizard for templates. But as I said, we can try to work around this, e.g. we could try to remove certain fields altogether and assemble the form field contents during the scaffolding phase of a template. A downside of this would be however, that it wouldn't be possible to let users manually create another project/namespace on openshift side to start over again in case they significantly messed up at one point. So this is clearly a trade-off we should be carefully evaluating before actually implementing this.
