### ISSUE TITLE
Confusing guide image shows pipelines but highlights topology

### ISSUE THREAD

**Issue by alexgroom** [redhat-scholars/backstage-workshop#25]
![](https://redhat-scholars.github.io/backstage-workshop/backstage-workshop/_images/pipelines_done.png)

Hmm, I find this screenshot very confusing and perhaps it is because it breaks my typical style guide for such activities. It shows pipelines but talks about topology. Again, stylistic personal choice but I would use the red box to highlight something that HAS been selected, so current state, and then use red arrow to highlight something I want the user to do now, so NEXT ACTION.

So in this case in the pipeline graphic (included) I would put a red arrow to topology and not use the red box, then to emphasize this, in the next screenshot showing the topology, put the red box around topology menu button.

You could even consider simply removing the pipeline graphic entirely since it is probably more than you need.

**Comment by joshix** [comment]
Route now goes from backstage create page -> pipelines link -> OCP pipelines view. Screenshot updated to indicate pipelines link in Backstage and pipelines in left nav of OCP. Not adopting arrow.
