### ISSUE TITLE
VSCode commit action needs to first select source control

### ISSUE THREAD

**Issue by alexgroom** [redhat-scholars/backstage-workshop#29]
![gh2](https://user-images.githubusercontent.com/9285462/235196046-2196fe4c-151e-4a54-8446-4ff979ea0d0c.png)

I have added and extra box on this image to show a step that is not described in the guide, you have to first select source control. People familiar with VSCode will get this, but for others they will be lost. However the image is now covered in boxes so maybe use an arrow to indicate the [+] selection?

**Comment by joshix** [comment]
Fixed with documentation note and screenshot in https://github.com/redhat-scholars/backstage-workshop/commit/6a18ab36dfd3e15caf52ced1daec22426c9f268b
