### ISSUE TITLE
Please add more explanation for this Optional reconnect task

### ISSUE THREAD

**Issue by alexgroom** [redhat-scholars/backstage-workshop#32]
"Optionally, reconnect the backend component with the gateway component to make the National Parks dataset visible again:

curl poi-gateway-app:8080/backend/register/poi-backend?endpoint=http://poi-backend-app:8080"

---
I don't understand on what optional circumstances I should perform this curl, nor do i understand what it means by "making the dataset visible again" Please can we have more explanation here.

I also see no output from my curl command and the guide does not explain what I should see.

On the plus side I did get a Milan pin dropped on the map so I'm thinking this worked for me, so it is a shame that the optional steps confused.

**Comment by joshix** [comment]
Alex: we have planned to expand the context around this. Short form is that when we add the custom point API, we restart the gateway pod. The gateway pod's list of backend endpoints is not persistent. The new pod doesn't know about the national parks backend unless you add it back to the gateway's list of backends.

@hpgrahsl is this something we could fix with low effort in the gateway, so that it maintains the list of backends even after we add the custom datapoint?

**Comment by alexgroom** [comment]
I don't think people will have a problem about doing something here, I just think as it stands the instructions are confusing and involve too much internal info with the app. After all it this app's behaviour is not really relevant but the golden path process is. Make sure the minutiae of one doesn't over shadow the other.

You could just say, "heh, we have a really simple app here, and since we have made a change we now need to restart or reset things so do this action XXX" might be a lot better way to explain, without really going into details. 

The word "Optionally" is incredibly confusing in a lab scenario when there is already a lot new stuff to see, because do you do it or not, and what happens if you do, or do not. Try and take that decision process away please.

**Comment by joshix** [comment]
planned fix: gateway polls for backend at WKL.

**Comment by hpgrahsl** [comment]
yes @joshix see this issue here https://github.com/hpgrahsl/rhsummit23-backstage-gpts/issues/24 and a PR is underway to support backend auto-registration during gateway bootstrap

**Comment by hpgrahsl** [comment]
addressed by https://github.com/hpgrahsl/rhsummit23-backstage-gpts/pull/27
