### ISSUE TITLE
Pipeline Status link is wrong

### ISSUE THREAD

**Issue by jayfray12** [redhat-scholars/backstage-workshop#38]
In the new cluster after creating the Gateway template the link to the pipeline status gives me a 404.
It should be:
https://console-openshift-console.**apps**.summit23bis.17gd.p1.openshiftapps.com/dev-pipelines/ns/jayfray12

But the link is pointing to:
https://console-openshift-console.summit23bis.17gd.p1.openshiftapps.com/dev-pipelines/ns/jayfray12/

**Comment by ryanj** [comment]
Thanks for reporting this one!

I have fixed the templates and my patched my ansible script.  
This should be resolved
