### ISSUE TITLE
Gateway repo needs unprotected main branch

### ISSUE THREAD

**Issue by jayfray12** [redhat-scholars/backstage-workshop#39]
When following the steps to launch DevSpaces and push code I get the following when trying to sync the changes:

![image](https://user-images.githubusercontent.com/38667521/236317005-d44e27f7-f031-4489-945b-e41e8f34d632.png)

The main branch needs to be unprotected and this should work

**Comment by ryanj** [comment]
The doc was out of date with our previous cluster info.  

I've updated the doc with new instructions:
"Make sure to click on *Grant* next to the *Summit23JanusN* GitHub Org before approving Dev Spaces access"

This should fix the issue for other testers.

**Comment by joshix** [comment]
Problem here seems to be documentation out of sync causing a user error. User must Grant to appropriate GH Org before editing and pushing with Dev Spaces. Documentation updated for latest GH Org.
