### ISSUE TITLE
Pipeline build does not trigger a new Deployment (CH4)

### ISSUE THREAD

**Issue by ryanj** [redhat-scholars/backstage-workshop#49]
After committing my change to the Gateway component, and after the pipeline run finishes successfully, the new image is not automatically promoted.

Currently, the user must delete a pod in order to trigger a redeploy of the new gateway image: https://redhat-scholars.github.io/backstage-workshop/backstage-workshop/04-development.html#validate_changes

Should we automatically deploy a new image after a successful build?  If not, is there a better way to trigger a new deployment (instead of deleting a pod)?

**Comment by ryanj** [comment]
Running `oc rollout restart deploy/ryanj-poi-gateway-app` will start the deployment.  Maybe I need to run this via a new Task?

**Comment by blues-man** [comment]
Yes, see the Java example week https://redhat-scholars.github.io/openshift-starter-guides/rhs-openshift-starter-guides/4.11/nationalparks-pipeline.html#create_your_pipeline

**Comment by ryanj** [comment]
Thanks! This should be resolved
